services:
  digitalhomelibrary.trackingbooks:
    image: ${DOCKER_REGISTRY-}digitalhomelibrarytrackingbooks
    build:
      context: .
      dockerfile: DigitalHomeLibrary.TrackingBooks/Dockerfile

  digitalhomelibrary.digitalbooksstorage:
    image: ${DOCKER_REGISTRY-}digitalhomelibrarydigitalbooksstorage
    build:
      context: .
      dockerfile: DigitalHomeLibrary.DigitalBooksStorage/Dockerfile
